### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by khrj** [golddranks/binary_macros#4]
Hi, I came across this crate today and realised that it doesn't compile on Rust 1.51.0 

```rust
error: proc-macro derive panicked
  --> signature_verifier/src/constants.rs:1:43
   |
1  |   pub const REPL_DEPLOY_PUBLIC_KEY: &[u8] = base64!(
   |  ___________________________________________^
2  | |     "MIIECgKCBAEAswkDXZlAqW1UpGiLFBW1ohSvUIqqcwrOt1ubbWrltrYT+3SQV24C\
3  | | Su9j93+DX9tsFBuVDE3DSutddBmdWh0zFxDdSO+uA8JBJki9GfHNoynFcPLl3AxA\
4  | | 4iUh6nD6uSdXIGkJaJ+U8/Jix2AXS7Qk5Jfoktx88GtKoHAwznmfxdJwrFeiX8D8\
...  |
23 | | yggLIsW8CUnOIhj0AKovh9OvyC//N/GRLQIDAQAB"
24 | | );
   | |_^
   |
   = help: message: Parse error: DecodeError { position: 1424, kind: Length }
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc-macro derive panicked
  --> signature_verifier/src/constants.rs:1:43
   |
1  |   pub const REPL_DEPLOY_PUBLIC_KEY: &[u8] = base64!(
   |  ___________________________________________^
2  | |     "MIIECgKCBAEAswkDXZlAqW1UpGiLFBW1ohSvUIqqcwrOt1ubbWrltrYT+3SQV24C\
3  | | Su9j93+DX9tsFBuVDE3DSutddBmdWh0zFxDdSO+uA8JBJki9GfHNoynFcPLl3AxA\
4  | | 4iUh6nD6uSdXIGkJaJ+U8/Jix2AXS7Qk5Jfoktx88GtKoHAwznmfxdJwrFeiX8D8\
...  |
23 | | yggLIsW8CUnOIhj0AKovh9OvyC//N/GRLQIDAQAB"
24 | | );
   | |_^
   |
   = help: message: Parse error: DecodeError { position: 1424, kind: Length }
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `proc_macro_call` in this scope
  --> signature_verifier/src/constants.rs:1:43
   |
1  |   pub const REPL_DEPLOY_PUBLIC_KEY: &[u8] = base64!(
   |  ___________________________________________^
2  | |     "MIIECgKCBAEAswkDXZlAqW1UpGiLFBW1ohSvUIqqcwrOt1ubbWrltrYT+3SQV24C\
3  | | Su9j93+DX9tsFBuVDE3DSutddBmdWh0zFxDdSO+uA8JBJki9GfHNoynFcPLl3AxA\
4  | | 4iUh6nD6uSdXIGkJaJ+U8/Jix2AXS7Qk5Jfoktx88GtKoHAwznmfxdJwrFeiX8D8\
...  |
23 | | yggLIsW8CUnOIhj0AKovh9OvyC//N/GRLQIDAQAB"
24 | | );
   | |_^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `proc_macro_call` in this scope
  --> signature_verifier/src/constants.rs:1:43
   |
1  |   pub const REPL_DEPLOY_PUBLIC_KEY: &[u8] = base64!(
   |  ___________________________________________^
2  | |     "MIIECgKCBAEAswkDXZlAqW1UpGiLFBW1ohSvUIqqcwrOt1ubbWrltrYT+3SQV24C\
3  | | Su9j93+DX9tsFBuVDE3DSutddBmdWh0zFxDdSO+uA8JBJki9GfHNoynFcPLl3AxA\
4  | | 4iUh6nD6uSdXIGkJaJ+U8/Jix2AXS7Qk5Jfoktx88GtKoHAwznmfxdJwrFeiX8D8\
...  |
23 | | yggLIsW8CUnOIhj0AKovh9OvyC//N/GRLQIDAQAB"
24 | | );
   | |_^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
